### ISSUE TITLE
UMLS graph code

### ISSUE THREAD

**Issue by Michelle-Mings** [TGoldsack1/Enhancing_Biomedical_Lay_Summarisation_with_External_Knowledge_Graphs#1]
Great paper! Would you mind sharing the code used to construct our graphs and features?

**Comment by TGoldsack1** [comment]
Many thanks! I have just added some code to the "graph construction" folder alongside a README describing the process - please feel free to take a look at this and let me know if you have any questions.

**Comment by Michelle-Mings** [comment]
Thank you for your prompt response! In your paper, you mentioned that you generate embeddings for graph features using SciBERT. Could you please share the code for generating embeddings based on their textual content as well? Also, I observed that some metadata, such as titles and years of the elife data, is missing from the eLife data folder. Could you kindly provide that information as well? Thanks a lot!

**Comment by TGoldsack1** [comment]
Oh yes, thanks for pointing this out! I've just added the feature extraction to the "graph construction" folder. Regarding the eLife data - you can download it from [this repository](https://github.com/TGoldsack1/Corpora_for_Lay_Summarisation?tab=readme-ov-file) we where publish the original dataset (including metadata).
