### ISSUE TITLE
ROGUE-L score

### ISSUE THREAD

**Issue by salvatoreferragamo** [TGoldsack1/Enhancing_Biomedical_Lay_Summarisation_with_External_Knowledge_Graphs#2]
can you share the code about how you calculate the ROUGE-L score ?

**Comment by TGoldsack1** [comment]
Hi! For how we calculate the ROUGE-L scores, you can refer to [this script](https://github.com/TGoldsack1/BioLaySumm2023-evaluation_scripts/blob/master/evaluate_st1.py) in a different repo.
Hope this helps.
